### Home
GET http://localhost:3000/

### Obtener todos los productos
GET http://localhost:3000/api/products

### Obtener producto por id
GET http://localhost:3000/api/products/B6ZTyKArLYhI1jUcmV5A

### Crear nuevo producto
POST http://localhost:3000/api/products/create
Content-Type: application/json

{
  "nombre": "fideos",
  "precio": "1900",
  "categoria": "alimentos"
}

### Eliminar producto por id
DELETE http://localhost:3000/api/products/WxaHcA6lVbxVQQ0gxmBA