### Home
GET http://localhost:3000/

### Obtener todos los productos
GET http://localhost:3000/api/products

### Obtener producto por id
GET http://localhost:3000/api/products/1

### Crear nuevo producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "title": "Men T-Shirt",
  "price": 0.1,
  "category": "men's clothing"
}

### Eliminar producto por id
DELETE http://localhost:3000/api/products/2